CREATE TABLE `general_settings` (
	`id` int NOT NULL DEFAULT 1,
	`header_logo_url` text,
	`header_logo_storage_key` varchar(512),
	`footer_logo_url` text,
	`footer_logo_storage_key` varchar(512),
	`favicon_url` text,
	`favicon_storage_key` varchar(512),
	`company_name` varchar(255),
	`company_description` mediumtext,
	`address` text,
	`phone` varchar(100),
	`email` varchar(320),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`facebook_url` text,
	`instagram_url` text,
	`twitter_url` text,
	`youtube_url` text,
	`tiktok_url` text,
	`linkedin_url` text,
	`website_url` text,
	`website_title` varchar(255),
	`seo_title` varchar(255),
	`seo_description` text,
	`seo_content` mediumtext,
	`seo_keywords` text,
	`open_graph_title` varchar(255),
	`open_graph_description` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `general_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `general_settings_singleton` CHECK(`general_settings`.`id` = 1)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
