/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GetSupportRouteImport } from './routes/get-support'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as InviteUmangaRouteImport } from './routes/invite-umanga'
import { Route as PartnerWithUsRouteImport } from './routes/partner-with-us'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShareYourStoryRouteImport } from './routes/share-your-story'
import { Route as SupportUsRouteImport } from './routes/support-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as OurWorkIndexRouteImport } from './routes/our-work/index'
import { Route as OurWorkSlugRouteImport } from './routes/our-work/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GetSupportRoute = GetSupportRouteImport.update({
  id: '/get-support',
  path: '/get-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteUmangaRoute = InviteUmangaRouteImport.update({
  id: '/invite-umanga',
  path: '/invite-umanga',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/partner-with-us',
  path: '/partner-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYourStoryRoute = ShareYourStoryRouteImport.update({
  id: '/share-your-story',
  path: '/share-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportUsRoute = SupportUsRouteImport.update({
  id: '/support-us',
  path: '/support-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkIndexRoute = OurWorkIndexRouteImport.update({
  id: '/our-work/',
  path: '/our-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/our-work/$slug',
  path: '/our-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/news/': typeof NewsIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/news': typeof NewsIndexRoute
  '/our-work': typeof OurWorkIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/news/': typeof NewsIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/news/'
    | '/our-work/'
    | '/resources/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/news'
    | '/our-work'
    | '/resources'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/news/'
    | '/our-work/'
    | '/resources/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  GetSupportRoute: typeof GetSupportRoute
  ImpactRoute: typeof ImpactRoute
  InviteUmangaRoute: typeof InviteUmangaRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PrivacyRoute: typeof PrivacyRoute
  ShareYourStoryRoute: typeof ShareYourStoryRoute
  SupportUsRoute: typeof SupportUsRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OurWorkSlugRoute: typeof OurWorkSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OurWorkIndexRoute: typeof OurWorkIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-support': {
      id: '/get-support'
      path: '/get-support'
      fullPath: '/get-support'
      preLoaderRoute: typeof GetSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-umanga': {
      id: '/invite-umanga'
      path: '/invite-umanga'
      fullPath: '/invite-umanga'
      preLoaderRoute: typeof InviteUmangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-us': {
      id: '/partner-with-us'
      path: '/partner-with-us'
      fullPath: '/partner-with-us'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-your-story': {
      id: '/share-your-story'
      path: '/share-your-story'
      fullPath: '/share-your-story'
      preLoaderRoute: typeof ShareYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-us': {
      id: '/support-us'
      path: '/support-us'
      fullPath: '/support-us'
      preLoaderRoute: typeof SupportUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/': {
      id: '/our-work/'
      path: '/our-work'
      fullPath: '/our-work/'
      preLoaderRoute: typeof OurWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/our-work/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  GetSupportRoute: GetSupportRoute,
  ImpactRoute: ImpactRoute,
  InviteUmangaRoute: InviteUmangaRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PrivacyRoute: PrivacyRoute,
  ShareYourStoryRoute: ShareYourStoryRoute,
  SupportUsRoute: SupportUsRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
  NewsSlugRoute: NewsSlugRoute,
  OurWorkSlugRoute: OurWorkSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  OurWorkIndexRoute: OurWorkIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
