/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GetSupportRouteImport } from './routes/get-support'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as InviteUmangaRouteImport } from './routes/invite-umanga'
import { Route as PartnerWithUsRouteImport } from './routes/partner-with-us'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShareYourStoryRouteImport } from './routes/share-your-story'
import { Route as SupportUsRouteImport } from './routes/support-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as OurWorkIndexRouteImport } from './routes/our-work/index'
import { Route as OurWorkSlugRouteImport } from './routes/our-work/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin/_protected/dashboard'
import { Route as AdminProtectedGalleryRouteImport } from './routes/admin/_protected/gallery'
import { Route as AdminProtectedInboxRouteImport } from './routes/admin/_protected/inbox'
import { Route as AdminProtectedNewsEventsRouteImport } from './routes/admin/_protected/news-events'
import { Route as AdminProtectedOurWorkRouteImport } from './routes/admin/_protected/our-work'
import { Route as AdminProtectedResourcesRouteImport } from './routes/admin/_protected/resources'
import { Route as AdminProtectedStoriesRouteImport } from './routes/admin/_protected/stories'
import { Route as AdminProtectedCmsIndexRouteImport } from './routes/admin/_protected/cms/index'
import { Route as AdminProtectedCmsGeneralSettingsRouteImport } from './routes/admin/_protected/cms/general-settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GetSupportRoute = GetSupportRouteImport.update({
  id: '/get-support',
  path: '/get-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteUmangaRoute = InviteUmangaRouteImport.update({
  id: '/invite-umanga',
  path: '/invite-umanga',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/partner-with-us',
  path: '/partner-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareYourStoryRoute = ShareYourStoryRouteImport.update({
  id: '/share-your-story',
  path: '/share-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportUsRoute = SupportUsRouteImport.update({
  id: '/support-us',
  path: '/support-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AdminRouteRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkIndexRoute = OurWorkIndexRouteImport.update({
  id: '/our-work/',
  path: '/our-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/our-work/$slug',
  path: '/our-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedGalleryRoute = AdminProtectedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedInboxRoute = AdminProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedNewsEventsRoute =
  AdminProtectedNewsEventsRouteImport.update({
    id: '/news-events',
    path: '/news-events',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedOurWorkRoute = AdminProtectedOurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedResourcesRoute = AdminProtectedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedStoriesRoute = AdminProtectedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedCmsIndexRoute = AdminProtectedCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedCmsGeneralSettingsRoute =
  AdminProtectedCmsGeneralSettingsRouteImport.update({
    id: '/cms/general-settings',
    path: '/cms/general-settings',
    getParentRoute: () => AdminProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/gallery': typeof AdminProtectedGalleryRoute
  '/admin/inbox': typeof AdminProtectedInboxRoute
  '/admin/news-events': typeof AdminProtectedNewsEventsRoute
  '/admin/our-work': typeof AdminProtectedOurWorkRoute
  '/admin/resources': typeof AdminProtectedResourcesRoute
  '/admin/stories': typeof AdminProtectedStoriesRoute
  '/admin/cms/general-settings': typeof AdminProtectedCmsGeneralSettingsRoute
  '/admin/cms/': typeof AdminProtectedCmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AdminIndexRoute
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/news': typeof NewsIndexRoute
  '/our-work': typeof OurWorkIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/gallery': typeof AdminProtectedGalleryRoute
  '/admin/inbox': typeof AdminProtectedInboxRoute
  '/admin/news-events': typeof AdminProtectedNewsEventsRoute
  '/admin/our-work': typeof AdminProtectedOurWorkRoute
  '/admin/resources': typeof AdminProtectedResourcesRoute
  '/admin/stories': typeof AdminProtectedStoriesRoute
  '/admin/cms/general-settings': typeof AdminProtectedCmsGeneralSettingsRoute
  '/admin/cms': typeof AdminProtectedCmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/get-support': typeof GetSupportRoute
  '/impact': typeof ImpactRoute
  '/invite-umanga': typeof InviteUmangaRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/privacy': typeof PrivacyRoute
  '/share-your-story': typeof ShareYourStoryRoute
  '/support-us': typeof SupportUsRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/news/': typeof NewsIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/gallery': typeof AdminProtectedGalleryRoute
  '/admin/_protected/inbox': typeof AdminProtectedInboxRoute
  '/admin/_protected/news-events': typeof AdminProtectedNewsEventsRoute
  '/admin/_protected/our-work': typeof AdminProtectedOurWorkRoute
  '/admin/_protected/resources': typeof AdminProtectedResourcesRoute
  '/admin/_protected/stories': typeof AdminProtectedStoriesRoute
  '/admin/_protected/cms/general-settings': typeof AdminProtectedCmsGeneralSettingsRoute
  '/admin/_protected/cms/': typeof AdminProtectedCmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/admin/'
    | '/news/'
    | '/our-work/'
    | '/resources/'
    | '/stories/'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/inbox'
    | '/admin/news-events'
    | '/admin/our-work'
    | '/admin/resources'
    | '/admin/stories'
    | '/admin/cms/general-settings'
    | '/admin/cms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/admin'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/news'
    | '/our-work'
    | '/resources'
    | '/stories'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/inbox'
    | '/admin/news-events'
    | '/admin/our-work'
    | '/admin/resources'
    | '/admin/stories'
    | '/admin/cms/general-settings'
    | '/admin/cms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/get-support'
    | '/impact'
    | '/invite-umanga'
    | '/partner-with-us'
    | '/privacy'
    | '/share-your-story'
    | '/support-us'
    | '/terms'
    | '/volunteer'
    | '/admin/_protected'
    | '/news/$slug'
    | '/our-work/$slug'
    | '/resources/$slug'
    | '/stories/$slug'
    | '/admin/'
    | '/news/'
    | '/our-work/'
    | '/resources/'
    | '/stories/'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/gallery'
    | '/admin/_protected/inbox'
    | '/admin/_protected/news-events'
    | '/admin/_protected/our-work'
    | '/admin/_protected/resources'
    | '/admin/_protected/stories'
    | '/admin/_protected/cms/general-settings'
    | '/admin/_protected/cms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  GetSupportRoute: typeof GetSupportRoute
  ImpactRoute: typeof ImpactRoute
  InviteUmangaRoute: typeof InviteUmangaRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PrivacyRoute: typeof PrivacyRoute
  ShareYourStoryRoute: typeof ShareYourStoryRoute
  SupportUsRoute: typeof SupportUsRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OurWorkSlugRoute: typeof OurWorkSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OurWorkIndexRoute: typeof OurWorkIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-support': {
      id: '/get-support'
      path: '/get-support'
      fullPath: '/get-support'
      preLoaderRoute: typeof GetSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-umanga': {
      id: '/invite-umanga'
      path: '/invite-umanga'
      fullPath: '/invite-umanga'
      preLoaderRoute: typeof InviteUmangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-us': {
      id: '/partner-with-us'
      path: '/partner-with-us'
      fullPath: '/partner-with-us'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-your-story': {
      id: '/share-your-story'
      path: '/share-your-story'
      fullPath: '/share-your-story'
      preLoaderRoute: typeof ShareYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-us': {
      id: '/support-us'
      path: '/support-us'
      fullPath: '/support-us'
      preLoaderRoute: typeof SupportUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/': {
      id: '/our-work/'
      path: '/our-work'
      fullPath: '/our-work/'
      preLoaderRoute: typeof OurWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/our-work/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/gallery': {
      id: '/admin/_protected/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminProtectedGalleryRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/inbox': {
      id: '/admin/_protected/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminProtectedInboxRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/news-events': {
      id: '/admin/_protected/news-events'
      path: '/news-events'
      fullPath: '/admin/news-events'
      preLoaderRoute: typeof AdminProtectedNewsEventsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/our-work': {
      id: '/admin/_protected/our-work'
      path: '/our-work'
      fullPath: '/admin/our-work'
      preLoaderRoute: typeof AdminProtectedOurWorkRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/resources': {
      id: '/admin/_protected/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminProtectedResourcesRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/stories': {
      id: '/admin/_protected/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminProtectedStoriesRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/cms/': {
      id: '/admin/_protected/cms/'
      path: '/cms'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminProtectedCmsIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/cms/general-settings': {
      id: '/admin/_protected/cms/general-settings'
      path: '/cms/general-settings'
      fullPath: '/admin/cms/general-settings'
      preLoaderRoute: typeof AdminProtectedCmsGeneralSettingsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedGalleryRoute: typeof AdminProtectedGalleryRoute
  AdminProtectedInboxRoute: typeof AdminProtectedInboxRoute
  AdminProtectedNewsEventsRoute: typeof AdminProtectedNewsEventsRoute
  AdminProtectedOurWorkRoute: typeof AdminProtectedOurWorkRoute
  AdminProtectedResourcesRoute: typeof AdminProtectedResourcesRoute
  AdminProtectedStoriesRoute: typeof AdminProtectedStoriesRoute
  AdminProtectedCmsGeneralSettingsRoute: typeof AdminProtectedCmsGeneralSettingsRoute
  AdminProtectedCmsIndexRoute: typeof AdminProtectedCmsIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedGalleryRoute: AdminProtectedGalleryRoute,
  AdminProtectedInboxRoute: AdminProtectedInboxRoute,
  AdminProtectedNewsEventsRoute: AdminProtectedNewsEventsRoute,
  AdminProtectedOurWorkRoute: AdminProtectedOurWorkRoute,
  AdminProtectedResourcesRoute: AdminProtectedResourcesRoute,
  AdminProtectedStoriesRoute: AdminProtectedStoriesRoute,
  AdminProtectedCmsGeneralSettingsRoute: AdminProtectedCmsGeneralSettingsRoute,
  AdminProtectedCmsIndexRoute: AdminProtectedCmsIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  GetSupportRoute: GetSupportRoute,
  ImpactRoute: ImpactRoute,
  InviteUmangaRoute: InviteUmangaRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PrivacyRoute: PrivacyRoute,
  ShareYourStoryRoute: ShareYourStoryRoute,
  SupportUsRoute: SupportUsRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
  NewsSlugRoute: NewsSlugRoute,
  OurWorkSlugRoute: OurWorkSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  OurWorkIndexRoute: OurWorkIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
